name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - pytest
  - mdanalysis
  - nglview
  - nbsphinx
  - ipython


    # Pip-only installs
  #- pip:

